### ISSUE TITLE
Test package gluon-ebtables-segment-mld

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#13]
[Link](https://gluon.readthedocs.io/en/v2016.2/package/gluon-ebtables-segment-mld.html)

**Comment by lemoer** [comment]
This may reduce the "groundnoise"

**Comment by lemoer** [comment]
We should really consider use this, as a a lot of our groundnoise is actually mld.

**Comment by 1977er** [comment]
You have my blessings. ;)

**Comment by AiyionPrime** [comment]
Missing mrd is no problem?

*Das mrd stark abwesend ist, ist uns egal?

**Comment by lemoer** [comment]
@AiyionPrime could you elaborate?

**Comment by AiyionPrime** [comment]
Possible that we simply do not care;
but in case someone of our 2000 clients is using his freifunk-node in a more sophisticated manner than just in order to provide a guest wifi; we should at least consider writing a memo onto the mailing list that we'll let the routers drop certain mld messages.

Using the package may lead snooping switches and routers attached to possibly miss, that the connected freifunk node is a multicast router and may therefore fall back to eg. unicast messages to a bunch of possible recipients in the freifunk-network;
I'm not sure wether someones actually streaming something into the net, but see no reason why not.

Maybe you're right and its unlikely that someones using this.

**Comment by lemoer** [comment]
It would be nice to measure the effect on the groundnoise. So it would be nice, if we begin to measure the groundnoise min ~1week before we start to distribute this update in stable branch.

**Comment by lemoer** [comment]
It's no own package any more since fe186077714a346da751daef79d238dab95c6263 and upstream https://github.com/freifunk-gluon/gluon/commit/17370d8462637a7d53bc1705e49e542acd92455e.
